"""Seed market events and news templates."""

import os
import sys

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../.."))

from db.models import MarketEvent, NewsTemplate, FactorDefinition

VALID_LINKED_DRIVERS = {
    "news_severity", "earnings_surprise", "economic_outlook",
    "guidance", "technical_momentum", "value_opportunity", "institutional_buying",
}

TEMPLATE_VARIABLES = {
    "{company}": "Company name (e.g. 'First National Bank')",
    "{product_name}": "Product being launched/recalled",
    "{defect}": "Defect description",
    "{eps}": "Actual EPS value",
    "{consensus}": "Consensus EPS estimate",
    "{pct}": "Percentage change amount",
    "{amount}": "Dividend amount per share",
    "{bps}": "Basis points change",
    "{industry}": "Industry name (e.g. 'Technology')",
    "{name}": "Person name",
    "{reason}": "Reason description",
    "{allegation}": "Allegation description",
    "{technology}": "Technology/patent description",
    "{indicator}": "Economic indicator name",
}

MARKET_EVENTS = [
    # ── PRICE EVENTS (temporary price drivers only, no structural effect) ──
    {
        "name": "Earnings Beat",
        "category": "earnings",
        "scope": "company",
        "severity_range": "10..40",
        "sentiment": "positive",
        "duration_days": 10,
        "decay_rate": 0.20,
        "probability_weight": 0.15,
        "news_type": "price",
        "effect_profile": {"earnings_surprise": 0.5, "news_severity": 0.3},
    },
    {
        "name": "Earnings Miss",
        "category": "earnings",
        "scope": "company",
        "severity_range": "15..50",
        "sentiment": "negative",
        "duration_days": 12,
        "decay_rate": 0.18,
        "probability_weight": 0.12,
        "news_type": "price",
        "effect_profile": {"earnings_surprise": -0.5, "news_severity": -0.4},
    },
    {
        "name": "Guidance Raised",
        "category": "guidance",
        "scope": "company",
        "severity_range": "10..30",
        "sentiment": "positive",
        "duration_days": 15,
        "decay_rate": 0.15,
        "probability_weight": 0.08,
        "news_type": "price",
        "effect_profile": {"guidance": 0.6, "news_severity": 0.3},
    },
    {
        "name": "Trade Tariff Imposed",
        "category": "trade",
        "scope": "industry",
        "severity_range": "20..50",
        "sentiment": "negative",
        "duration_days": 60,
        "decay_rate": 0.04,
        "probability_weight": 0.03,
        "news_type": "price",
        "effect_profile": {"news_severity": -0.5, "economic_outlook": -0.3},
    },
    {
        "name": "Labor Strike",
        "category": "labor",
        "scope": "industry",
        "severity_range": "20..50",
        "sentiment": "negative",
        "duration_days": 20,
        "decay_rate": 0.12,
        "probability_weight": 0.02,
        "news_type": "price",
        "effect_profile": {"news_severity": -0.4, "guidance": -0.5},
    },
    {
        "name": "Interest Rate Hike",
        "category": "monetary",
        "scope": "market",
        "severity_range": "30..70",
        "sentiment": "negative",
        "duration_days": 30,
        "decay_rate": 0.08,
        "probability_weight": 0.06,
        "news_type": "price",
        "effect_profile": {"economic_outlook": -0.5, "news_severity": -0.3},
    },
    {
        "name": "Interest Rate Cut",
        "category": "monetary",
        "scope": "market",
        "severity_range": "20..50",
        "sentiment": "positive",
        "duration_days": 25,
        "decay_rate": 0.10,
        "probability_weight": 0.04,
        "news_type": "price",
        "effect_profile": {"economic_outlook": 0.5, "news_severity": 0.3},
    },
    {
        "name": "Bull Market Rally",
        "category": "macro",
        "scope": "market",
        "severity_range": "20..50",
        "sentiment": "positive",
        "duration_days": 35,
        "decay_rate": 0.07,
        "probability_weight": 0.04,
        "news_type": "price",
        "effect_profile": {"economic_outlook": 0.4, "technical_momentum": 0.5, "institutional_buying": 0.4},
    },
    {
        "name": "Geopolitical Crisis",
        "category": "geopolitics",
        "scope": "market",
        "severity_range": "40..80",
        "sentiment": "negative",
        "duration_days": 45,
        "decay_rate": 0.05,
        "probability_weight": 0.02,
        "news_type": "price",
        "effect_profile": {"economic_outlook": -0.6, "news_severity": -0.6, "institutional_buying": -0.5},
    },
    {
        "name": "Central Bank Policy Shift",
        "category": "monetary",
        "scope": "market",
        "severity_range": "15..45",
        "sentiment": "mixed",
        "duration_days": 20,
        "decay_rate": 0.12,
        "probability_weight": 0.04,
        "news_type": "price",
        "effect_profile": {"economic_outlook": 0.2, "news_severity": 0.2},
    },
    {
        "name": "Natural Disaster Impact",
        "category": "disaster",
        "scope": "market",
        "severity_range": "30..70",
        "sentiment": "negative",
        "duration_days": 20,
        "decay_rate": 0.10,
        "probability_weight": 0.01,
        "news_type": "price",
        "effect_profile": {"news_severity": -0.5, "economic_outlook": -0.3},
    },
    {
        "name": "Minor Competitor Emerges",
        "category": "competition",
        "scope": "company",
        "severity_range": "5..20",
        "sentiment": "negative",
        "duration_days": 20,
        "decay_rate": 0.12,
        "probability_weight": 0.03,
        "news_type": "price",
        "effect_profile": {"news_severity": -0.15},
    },
    # ── STRUCTURAL EVENTS (affect fundamental scores, no direct price drivers) ──
    {
        "name": "Regulatory Approval",
        "category": "regulation",
        "scope": "industry",
        "severity_range": "15..40",
        "sentiment": "positive",
        "duration_days": 60,
        "decay_rate": 0.04,
        "probability_weight": 0.03,
        "news_type": "structural",
        "effect_profile": {"moat_score": 0.3, "growth_potential": 0.25, "financial_quality": 0.2},
    },
    # ── BOTH EVENTS (structural + price drivers) ──
    {
        "name": "CEO Resignation",
        "category": "leadership",
        "scope": "company",
        "severity_range": "10..50",
        "sentiment": "negative",
        "duration_days": 15,
        "decay_rate": 0.15,
        "probability_weight": 0.02,
        "news_type": "both",
        "effect_profile": {"news_severity": -0.4, "guidance": -0.5, "management_quality": -0.4},
    },
    {
        "name": "Product Launch Success",
        "category": "product",
        "scope": "company",
        "severity_range": "20..60",
        "sentiment": "positive",
        "duration_days": 20,
        "decay_rate": 0.10,
        "probability_weight": 0.04,
        "news_type": "both",
        "effect_profile": {"news_severity": 0.5, "technical_momentum": 0.3, "growth_potential": 0.3, "innovation": 0.5},
    },
    {
        "name": "Product Recall",
        "category": "product",
        "scope": "company",
        "severity_range": "30..70",
        "sentiment": "negative",
        "duration_days": 25,
        "decay_rate": 0.12,
        "probability_weight": 0.03,
        "news_type": "both",
        "effect_profile": {"news_severity": -0.6, "guidance": -0.7, "moat_score": -0.3, "management_quality": -0.2},
    },
    {
        "name": "Dividend Hike",
        "category": "dividend",
        "scope": "company",
        "severity_range": "5..25",
        "sentiment": "positive",
        "duration_days": 8,
        "decay_rate": 0.25,
        "probability_weight": 0.06,
        "news_type": "both",
        "effect_profile": {"news_severity": 0.3, "guidance": 0.2, "fcf_quality": 0.15},
    },
    {
        "name": "Dividend Cut",
        "category": "dividend",
        "scope": "company",
        "severity_range": "15..45",
        "sentiment": "negative",
        "duration_days": 15,
        "decay_rate": 0.15,
        "probability_weight": 0.04,
        "news_type": "both",
        "effect_profile": {"news_severity": -0.5, "guidance": -0.6, "fcf_quality": -0.3},
    },
    {
        "name": "Patent Granted",
        "category": "legal",
        "scope": "company",
        "severity_range": "10..40",
        "sentiment": "positive",
        "duration_days": 30,
        "decay_rate": 0.08,
        "probability_weight": 0.03,
        "news_type": "both",
        "effect_profile": {"news_severity": 0.4, "technical_momentum": 0.2, "moat_score": 0.4, "intangibles": 0.8, "growth_potential": 0.2},
    },
    {
        "name": "Lawsuits Filed",
        "category": "legal",
        "scope": "company",
        "severity_range": "20..60",
        "sentiment": "negative",
        "duration_days": 40,
        "decay_rate": 0.05,
        "probability_weight": 0.02,
        "news_type": "both",
        "effect_profile": {"news_severity": -0.5, "management_quality": -0.25},
    },
    {
        "name": "Regulatory Change",
        "category": "regulation",
        "scope": "industry",
        "severity_range": "20..60",
        "sentiment": "negative",
        "duration_days": 45,
        "decay_rate": 0.06,
        "probability_weight": 0.05,
        "news_type": "both",
        "effect_profile": {"news_severity": -0.4, "economic_outlook": -0.2, "growth_potential": -0.2},
    },
    {
        "name": "Industry Boom",
        "category": "macro",
        "scope": "industry",
        "severity_range": "20..50",
        "sentiment": "positive",
        "duration_days": 40,
        "decay_rate": 0.07,
        "probability_weight": 0.04,
        "news_type": "both",
        "effect_profile": {"news_severity": 0.4, "economic_outlook": 0.3, "growth_potential": 0.3},
    },
    {
        "name": "Supply Chain Disruption",
        "category": "operations",
        "scope": "industry",
        "severity_range": "15..45",
        "sentiment": "negative",
        "duration_days": 30,
        "decay_rate": 0.10,
        "probability_weight": 0.06,
        "news_type": "both",
        "effect_profile": {"news_severity": -0.3, "guidance": -0.4, "financial_quality": -0.2},
    },
    {
        "name": "Technology Breakthrough",
        "category": "technology",
        "scope": "industry",
        "severity_range": "15..45",
        "sentiment": "positive",
        "duration_days": 35,
        "decay_rate": 0.08,
        "probability_weight": 0.03,
        "news_type": "both",
        "effect_profile": {"news_severity": 0.4, "technical_momentum": 0.3, "growth_potential": 0.4, "innovation": 0.6},
    },
    {
        "name": "Commodity Price Spike",
        "category": "commodity",
        "scope": "industry",
        "severity_range": "15..55",
        "sentiment": "mixed",
        "duration_days": 25,
        "decay_rate": 0.10,
        "probability_weight": 0.05,
        "news_type": "both",
        "effect_profile": {"news_severity": 0.2, "economic_outlook": -0.2, "financial_quality": -0.15},
    },
    {
        "name": "Consolidation Wave (M&A)",
        "category": "strategy",
        "scope": "industry",
        "severity_range": "10..35",
        "sentiment": "positive",
        "duration_days": 30,
        "decay_rate": 0.09,
        "probability_weight": 0.03,
        "news_type": "both",
        "effect_profile": {"news_severity": 0.3, "technical_momentum": 0.2, "moat_score": 0.3},
    },
    {
        "name": "Recession Fears",
        "category": "macro",
        "scope": "market",
        "severity_range": "40..80",
        "sentiment": "negative",
        "duration_days": 60,
        "decay_rate": 0.04,
        "probability_weight": 0.03,
        "news_type": "both",
        "effect_profile": {"economic_outlook": -0.7, "news_severity": -0.5, "institutional_buying": -0.4, "growth_potential": -0.3},
    },
    {
        "name": "Strong Competitor Entry",
        "category": "competition",
        "scope": "company",
        "severity_range": "20..60",
        "sentiment": "negative",
        "duration_days": 45,
        "decay_rate": 0.06,
        "probability_weight": 0.02,
        "news_type": "both",
        "effect_profile": {
            "news_severity": -0.4,
            "moat_score": -0.5,
            "market_share": -0.6,
            "growth_potential": -0.3,
        },
    },
]

NEWS_TEMPLATES = [
    {
        "category": "leadership",
        "sentiment": "negative",
        "severity_band": "medium",
        "linked_event_category": "leadership",
        "linked_driver": "news_severity",
        "template_text": "{company} CEO {name} resigns amid {reason}. Shares expected to face pressure.",
    },
    {
        "category": "product",
        "sentiment": "positive",
        "severity_band": "high",
        "linked_event_category": "product",
        "linked_driver": "news_severity",
        "template_text": "{company} launches {product_name}, analysts call it a game-changer.",
    },
    {
        "category": "product",
        "sentiment": "negative",
        "severity_band": "high",
        "linked_event_category": "product",
        "linked_driver": "news_severity",
        "template_text": "{company} recalls {product_name} due to {defect}. Stock under pressure.",
    },
    {
        "category": "earnings",
        "sentiment": "positive",
        "severity_band": "medium",
        "linked_event_category": "earnings",
        "linked_driver": "earnings_surprise",
        "template_text": "{company} beats estimates: EPS of {eps} vs consensus of {consensus}.",
    },
    {
        "category": "earnings",
        "sentiment": "negative",
        "severity_band": "medium",
        "linked_event_category": "earnings",
        "linked_driver": "earnings_surprise",
        "template_text": "{company} misses estimates: EPS of {eps} misses consensus of {consensus}.",
    },
    {
        "category": "dividend",
        "sentiment": "positive",
        "severity_band": "low",
        "linked_event_category": "dividend",
        "linked_driver": "news_severity",
        "template_text": "{company} raises dividend by {pct}% to {amount} per share.",
    },
    {
        "category": "dividend",
        "sentiment": "negative",
        "severity_band": "medium",
        "linked_event_category": "dividend",
        "linked_driver": "news_severity",
        "template_text": "{company} slashes dividend. Yield drops to {pct}%.",
    },
    {
        "category": "legal",
        "sentiment": "positive",
        "severity_band": "medium",
        "linked_event_category": "legal",
        "linked_driver": "news_severity",
        "template_text": "{company} awarded key patent for {technology}. Competitive moat strengthened.",
    },
    {
        "category": "legal",
        "sentiment": "negative",
        "severity_band": "medium",
        "linked_event_category": "legal",
        "linked_driver": "news_severity",
        "template_text": "Class-action lawsuit filed against {company} over {allegation}.",
    },
    {
        "category": "macro",
        "sentiment": "negative",
        "severity_band": "high",
        "linked_event_category": "macro",
        "linked_driver": "economic_outlook",
        "template_text": "Recession fears intensify as {indicator} signals contraction.",
    },
    {
        "category": "monetary",
        "sentiment": "negative",
        "severity_band": "medium",
        "linked_event_category": "monetary",
        "linked_driver": "economic_outlook",
        "template_text": "Central bank raises rates by {bps} bps. Markets react negatively.",
    },
    {
        "category": "monetary",
        "sentiment": "positive",
        "severity_band": "medium",
        "linked_event_category": "monetary",
        "linked_driver": "economic_outlook",
        "template_text": "Central bank cuts rates by {bps} bps in surprise move.",
    },
    {
        "category": "macro",
        "sentiment": "positive",
        "severity_band": "medium",
        "linked_event_category": "macro",
        "linked_driver": "economic_outlook",
        "template_text": "{industry} sector enters boom cycle as demand surges.",
    },
    {
        "category": "regulation",
        "sentiment": "negative",
        "severity_band": "medium",
        "linked_event_category": "regulation",
        "linked_driver": "news_severity",
        "template_text": "New regulations hit {industry} sector. Compliance costs expected to rise.",
    },
    {
        "category": "geopolitics",
        "sentiment": "negative",
        "severity_band": "high",
        "linked_event_category": "geopolitics",
        "linked_driver": "economic_outlook",
        "template_text": "Geopolitical tensions escalate. Safe-haven assets rally on uncertainty.",
    },
    # ── Competition templates ──────────────────────────────────────────
    {
        "category": "competition",
        "sentiment": "negative",
        "severity_band": "high",
        "linked_event_category": "competition",
        "linked_driver": "news_severity",
        "template_text": "{company} faces fierce new competition as {name} enters the market. Market share concerns mount.",
    },
    {
        "category": "competition",
        "sentiment": "negative",
        "severity_band": "high",
        "linked_event_category": "competition",
        "linked_driver": "news_severity",
        "template_text": "Industry disruptor {name} announces entry into {company}'s core market. Competitive moat under threat.",
    },
    {
        "category": "competition",
        "sentiment": "negative",
        "severity_band": "high",
        "linked_event_category": "competition",
        "linked_driver": "news_severity",
        "template_text": "Aggressive pricing from new rival {name} pressures {company}'s margins. Analysts cut estimates.",
    },
    {
        "category": "competition",
        "sentiment": "negative",
        "severity_band": "low",
        "linked_event_category": "competition",
        "linked_driver": "news_severity",
        "template_text": "Small startup {name} enters the fray, but analysts say {company}'s moat remains intact.",
    },
    {
        "category": "competition",
        "sentiment": "negative",
        "severity_band": "low",
        "linked_event_category": "competition",
        "linked_driver": "news_severity",
        "template_text": "A minor competitor has launched in {company}'s space. Near-term impact expected to be limited.",
    },
    # ── Regulatory Approval templates ──────────────────────────────────
    {
        "category": "regulation",
        "sentiment": "positive",
        "severity_band": "medium",
        "linked_event_category": "regulation",
        "linked_driver": "news_severity",
        "template_text": "Regulatory approval granted for key {industry} sector reforms. {company} stands to benefit significantly.",
    },
    {
        "category": "regulation",
        "sentiment": "positive",
        "severity_band": "medium",
        "linked_event_category": "regulation",
        "linked_driver": "news_severity",
        "template_text": "Favorable regulatory ruling strengthens {company}'s competitive position in {industry}.",
    },
]


# ── Industry-specific MarketEvents (company-scope, mixed sentiment) ──────
INDUSTRY_MARKET_EVENTS = [
    {"name": "Banking Sector Development", "category": "banking", "scope": "company",
     "severity_range": "15..45", "sentiment": "mixed", "duration_days": 15, "decay_rate": 0.12,
     "probability_weight": 0.04, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "financial_quality": 0.2}},
    {"name": "Technology Sector Development", "category": "technology", "scope": "company",
     "severity_range": "15..50", "sentiment": "mixed", "duration_days": 15, "decay_rate": 0.12,
     "probability_weight": 0.04, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "growth_potential": 0.25}},
    {"name": "Pharma Sector Development", "category": "pharma", "scope": "company",
     "severity_range": "15..50", "sentiment": "mixed", "duration_days": 18, "decay_rate": 0.10,
     "probability_weight": 0.04, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "moat_score": 0.2}},
    {"name": "FMCG Sector Development", "category": "fmcg", "scope": "company",
     "severity_range": "10..35", "sentiment": "mixed", "duration_days": 12, "decay_rate": 0.15,
     "probability_weight": 0.04, "news_type": "both",
     "effect_profile": {"news_severity": 0.2, "moat_score": 0.15}},
    {"name": "Auto Sector Development", "category": "auto", "scope": "company",
     "severity_range": "15..45", "sentiment": "mixed", "duration_days": 15, "decay_rate": 0.12,
     "probability_weight": 0.04, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "guidance": 0.2}},
    {"name": "Energy Sector Development", "category": "energy", "scope": "company",
     "severity_range": "20..55", "sentiment": "mixed", "duration_days": 20, "decay_rate": 0.10,
     "probability_weight": 0.04, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "economic_outlook": 0.2}},
    {"name": "Utilities Sector Development", "category": "utilities", "scope": "company",
     "severity_range": "10..30", "sentiment": "mixed", "duration_days": 20, "decay_rate": 0.08,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.2, "financial_quality": 0.15}},
    {"name": "Metals Sector Development", "category": "metals", "scope": "company",
     "severity_range": "15..50", "sentiment": "mixed", "duration_days": 18, "decay_rate": 0.10,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "economic_outlook": 0.15}},
    {"name": "Construction Sector Development", "category": "construction", "scope": "company",
     "severity_range": "15..40", "sentiment": "mixed", "duration_days": 20, "decay_rate": 0.10,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "guidance": 0.2}},
    {"name": "Real Estate Sector Development", "category": "realestate", "scope": "company",
     "severity_range": "15..40", "sentiment": "mixed", "duration_days": 20, "decay_rate": 0.10,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "financial_quality": 0.2}},
    {"name": "Telecom Sector Development", "category": "telecom", "scope": "company",
     "severity_range": "15..40", "sentiment": "mixed", "duration_days": 15, "decay_rate": 0.12,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "growth_potential": 0.2}},
    {"name": "Retail Sector Development", "category": "retail", "scope": "company",
     "severity_range": "15..40", "sentiment": "mixed", "duration_days": 12, "decay_rate": 0.15,
     "probability_weight": 0.04, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "moat_score": 0.15}},
    {"name": "Industrials Sector Development", "category": "industrials", "scope": "company",
     "severity_range": "15..40", "sentiment": "mixed", "duration_days": 18, "decay_rate": 0.10,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "guidance": 0.2}},
    {"name": "Chemicals Sector Development", "category": "chemicals", "scope": "company",
     "severity_range": "15..45", "sentiment": "mixed", "duration_days": 18, "decay_rate": 0.10,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "financial_quality": 0.15}},
    {"name": "Media Sector Development", "category": "media", "scope": "company",
     "severity_range": "15..40", "sentiment": "mixed", "duration_days": 12, "decay_rate": 0.15,
     "probability_weight": 0.03, "news_type": "both",
     "effect_profile": {"news_severity": 0.3, "growth_potential": 0.2}},
]

# ── Industry-specific NewsTemplates (15 per industry = 225 total) ─────────
INDUSTRY_NEWS_TEMPLATES = [
    # ── Banking & Financial Services ────────────────────────────────────
    {"category": "banking", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} reports strong growth in retail lending book. Asset quality remains stable."},
    {"category": "banking", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} net interest margin expands on lower cost of funds. Analysts turn bullish."},
    {"category": "banking", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} receives regulatory nod for expansion into new geographies."},
    {"category": "banking", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} digital banking platform crosses 10 million active users."},
    {"category": "banking", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} asset quality concerns mount as slippages rise in agri portfolio."},
    {"category": "banking", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} faces RBI scrutiny over governance lapses. Stock under pressure."},
    {"category": "banking", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} CASA ratio drops sharply as depositors chase higher yields elsewhere."},
    {"category": "banking", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} reduces stressed assets ratio below industry average. Credit costs moderate."},
    {"category": "banking", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} treasury losses mount as bond yields spike unexpectedly."},
    {"category": "banking", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} gains market share in home loans and auto finance segments."},
    {"category": "banking", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} sees moderate uptick in restructuring requests from SME borrowers."},
    {"category": "banking", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} successfully raises capital via QIP at premium. Strong institutional demand."},
    {"category": "banking", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} provisions rise sharply for a large corporate account turning NPA."},
    {"category": "banking", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} fee income grows 18% on strong advisory and forex business."},
    {"category": "banking", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "banking", "linked_driver": "news_severity",
     "template_text": "{company} under CBI investigation over alleged loan fraud. Management turmoil deepens."},

    # ── Information Technology / Software ───────────────────────────────
    {"category": "technology", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} signs multi-year digital transformation deal with global banking client."},
    {"category": "technology", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} faces visa curbs in key US market. Supply concerns loom."},
    {"category": "technology", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} GenAI platform wins enterprise adoption. Deal pipeline robust."},
    {"category": "technology", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} attrition rate spikes to 22%. Talent retention becomes key concern."},
    {"category": "technology", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} recognized as leader in Gartner Magic Quadrant for cloud services."},
    {"category": "technology", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} loses $200M contract as client moves to captive unit. Street disappointed."},
    {"category": "technology", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} announces aggressive share buyback. Management confident on growth."},
    {"category": "technology", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} faces pricing pressure in BFSI vertical. Margins under watch."},
    {"category": "technology", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} achieves highest-ever deal TCV in Q. Strong deal pipeline ahead."},
    {"category": "technology", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} data breach exposes customer information. Class action lawsuits expected."},
    {"category": "technology", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} expands into European market with new delivery center in Poland."},
    {"category": "technology", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} disappoints on growth guidance. Macro uncertainty cited for weak outlook."},
    {"category": "technology", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} subsidiary gets mega contract for smart city project in Southeast Asia."},
    {"category": "technology", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} sees slowdown in discretionary spending by US clients."},
    {"category": "technology", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "technology", "linked_driver": "news_severity",
     "template_text": "{company} launches indigenous chip design. Import substitution narrative boosts sentiment."},

    # ── Pharmaceuticals & Healthcare ────────────────────────────────────
    {"category": "pharma", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} receives USFDA approval for blockbuster generic. 180-day exclusivity window secured."},
    {"category": "pharma", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} manufacturing facility gets Form 483 observation from USFDA. Shares tumble."},
    {"category": "pharma", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} phase 3 trial meets primary endpoint. Path to regulatory filing cleared."},
    {"category": "pharma", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} key patent invalidated by court. Generic competition looms large."},
    {"category": "pharma", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} forays into biosimilars space. High-margin opportunity ahead."},
    {"category": "pharma", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} faces pricing pressure in US generics market. Erosion faster than expected."},
    {"category": "pharma", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} launches new drug in domestic market. Strong prescription uptake expected."},
    {"category": "pharma", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} R&D spend disappoints. Pipeline concerns weigh on valuations."},
    {"category": "pharma", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} gets tentative approval for ANDA in large addressable market."},
    {"category": "pharma", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} drug fails in late-stage trial. Multi-billion dollar opportunity slips away."},
    {"category": "pharma", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} receives EU GMP certification for injectables facility. Export potential unlocked."},
    {"category": "pharma", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} faces price cap by Indian government on essential medicines list."},
    {"category": "pharma", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} licensing deal with global pharma major for novel therapy. Milestone payments ahead."},
    {"category": "pharma", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} raw material costs surge. Gross margins under pressure this quarter."},
    {"category": "pharma", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "pharma", "linked_driver": "news_severity",
     "template_text": "{company} CDMO business wins marquee client. Order book fills up sharply."},

    # ── FMCG / Consumer Staples ─────────────────────────────────────────
    {"category": "fmcg", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} gains market share in core categories. Rural demand recovery supports growth."},
    {"category": "fmcg", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} volume growth disappoints as urban demand weakens."},
    {"category": "fmcg", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} enters adjacent category with strategic acquisition. Synergy benefits eyed."},
    {"category": "fmcg", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} input costs rise on commodity inflation. Margins likely to compress."},
    {"category": "fmcg", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} expands distribution network to 2 million retail touchpoints."},
    {"category": "fmcg", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} faces regulatory heat on misleading advertisement. Brand reputation at stake."},
    {"category": "fmcg", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} premium product portfolio sees strong growth. Mix improvement boosts margins."},
    {"category": "fmcg", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} aggressive price cuts fail to revive volumes. Competitive pressure intensifies."},
    {"category": "fmcg", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} e-commerce channel crosses 10% of total sales. Digital momentum building."},
    {"category": "fmcg", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} distributor unrest grows over margin compression. Channel health under watch."},
    {"category": "fmcg", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} flagship brand achieves top-of-mind recall in consumer survey."},
    {"category": "fmcg", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} private label competition from modern trade eats into market share."},
    {"category": "fmcg", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} gross margin expands on benign raw material costs and mix improvement."},
    {"category": "fmcg", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} product recall over quality concerns hits brand trust."},
    {"category": "fmcg", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "fmcg", "linked_driver": "news_severity",
     "template_text": "{company} sustainability initiative wins global recognition. ESG score improves."},

    # ── Automobiles & Auto Components ───────────────────────────────────
    {"category": "auto", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} domestic sales surge on new model launches. Market share improves."},
    {"category": "auto", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} production cut due to weak demand. Inventory days at elevated levels."},
    {"category": "auto", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} unveils electric vehicle platform. Long-term EV strategy gets thumbs up."},
    {"category": "auto", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} faces safety probe in overseas market. Recall costs may mount."},
    {"category": "auto", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} export orders book robust. Weak rupee adds to margin tailwind."},
    {"category": "auto", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} semiconductor supply woes persist. Production impacted for second quarter."},
    {"category": "auto", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} BS-VI transition complete. Product cycle positioned for volume recovery."},
    {"category": "auto", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} raw material costs inch up. Steel and aluminum prices bite margins."},
    {"category": "auto", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} aftermarket business grows 15%. High-margin parts revenue diversifies income."},
    {"category": "auto", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} joint venture partner exits. Strategic uncertainty clouds outlook."},
    {"category": "auto", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} certified pre-owned car business gains traction. High-margin growth engine."},
    {"category": "auto", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} discounting intensity increases. Realization per vehicle declines sequentially."},
    {"category": "auto", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} bags large government tender for electric buses. Order pipeline strengthens."},
    {"category": "auto", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} wage negotiation with union turns acrimonious. Strike risk elevated."},
    {"category": "auto", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "auto", "linked_driver": "news_severity",
     "template_text": "{company} hydrogen fuel cell pilot gains traction. Alternative tech roadmap emerging."},

    # ── Energy (Oil & Gas) ──────────────────────────────────────────────
    {"category": "energy", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} discovers new hydrocarbon reserve in KG basin. Potential recoverable reserves estimated at 50 MMBOE."},
    {"category": "energy", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} refining margins shrink sharply. GRM falls below breakeven on weak demand."},
    {"category": "energy", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} gas production ramps up from new field. Domestic output rises 12%."},
    {"category": "energy", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} oil spill incident triggers environmental penalty. Cleanup costs mount."},
    {"category": "energy", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} renewable energy capacity crosses 10 GW. Green transition on track."},
    {"category": "energy", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} windfall tax impact weighs on earnings. Government policy overhang persists."},
    {"category": "energy", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} marketing margins expand on stable fuel prices. Retail network growth drives volume."},
    {"category": "energy", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} E&P costs rise due to service inflation. Development capex may overshoot."},
    {"category": "energy", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} secures long-term LNG supply agreement. Gas sourcing visibility improves."},
    {"category": "energy", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} petrochemical crack spread weakens. Integration benefit narrows."},
    {"category": "energy", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} city gas distribution network expands to 15 new districts."},
    {"category": "energy", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} exploration write-downs on failed wells. Capex efficiency under scrutiny."},
    {"category": "energy", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} crude throughput at record levels. Plant utilization above 105%."},
    {"category": "energy", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} fuel retail margins squeezed as OMCs engage in price war."},
    {"category": "energy", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "energy", "linked_driver": "news_severity",
     "template_text": "{company} strategic stake sale in pipeline asset to monetize infrastructure. Debt reduction ahead."},

    # ── Utilities (Power/Gas/Water) ─────────────────────────────────────
    {"category": "utilities", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} power generation capacity expands with new renewable plant commissioning."},
    {"category": "utilities", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} plant load factor declines on weak power demand from industrial consumers."},
    {"category": "utilities", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} wins new power purchase agreement at favourable tariff. Revenue visibility improves."},
    {"category": "utilities", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} faces regulatory penalty for emission norm violations. Plant shutdown ordered."},
    {"category": "utilities", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} transmission loss reduces to record low. Operational efficiency improving."},
    {"category": "utilities", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} coal supply shortage hits generation. Inventory days fall to critical levels."},
    {"category": "utilities", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} smart metering rollout accelerates. Reduction in AT&C losses boosts margins."},
    {"category": "utilities", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} discom receivables mount. State government payment delays persist."},
    {"category": "utilities", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} secures green loan for renewable expansion. Cost of capital reduces."},
    {"category": "utilities", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} tariff revision petition rejected by regulator. Revenue growth capped."},
    {"category": "utilities", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} hydro power generation exceeds targets on good monsoon. Fuel cost savings flow through."},
    {"category": "utilities", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} gas-based plants stranded due to high LNG prices. Capacity under-utilized."},
    {"category": "utilities", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} debt refinancing completed. Annual interest cost savings of INR 200 Cr."},
    {"category": "utilities", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} open access power sales face competition. Industrial tariff structure under pressure."},
    {"category": "utilities", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "utilities", "linked_driver": "news_severity",
     "template_text": "{company} battery storage project gets viability gap funding. New revenue stream emerging."},

    # ── Metals & Mining ─────────────────────────────────────────────────
    {"category": "metals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} steel production hits record high on strong demand from infrastructure sector."},
    {"category": "metals", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} mining lease renewal delayed by state government. Operations may be impacted."},
    {"category": "metals", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} iron ore production ramps up from new mine. Cost advantages emerging."},
    {"category": "metals", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} faces anti-dumping duty in export market. Global trade tensions mount."},
    {"category": "metals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} aluminum business turns profitable on higher LME prices. Margin recovery underway."},
    {"category": "metals", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} power cost rises as coal linkage auction prices spike."},
    {"category": "metals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} value-added product share crosses 40%. Product mix improvement boosts realization."},
    {"category": "metals", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} furnace accident causes production loss. Safety protocols under review."},
    {"category": "metals", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} achieves lowest cost position among domestic peers. Structural cost advantage."},
    {"category": "metals", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} inventory builds up as export demand weakens. China dumping concerns rise."},
    {"category": "metals", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} secures iron ore mine auction. Raw material security improves significantly."},
    {"category": "metals", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} coking coal costs surge. Steel spreads compress sharply."},
    {"category": "metals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} expansion capex nearly complete. Volume growth to drive earnings from next quarter."},
    {"category": "metals", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} rail freight surcharge increase adds to logistics cost pressure."},
    {"category": "metals", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "metals", "linked_driver": "news_severity",
     "template_text": "{company} wins large export order for specialty steel grade. Global Tier-1 certification achieved."},

    # ── Construction & Infrastructure ───────────────────────────────────
    {"category": "construction", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} order inflow surges in roads and highways segment. Execution momentum strong."},
    {"category": "construction", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} receivables from government stretch to 180 days. Working capital cycle worsens."},
    {"category": "construction", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} bags HAM project worth INR 2,500 Cr. Strong IRR visibility."},
    {"category": "construction", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} arbitration award delayed. Cash flow from stuck projects remains blocked."},
    {"category": "construction", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} executes highest ever quarterly revenue. Margins improve on scale benefits."},
    {"category": "construction", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} labour availability issues delay project timelines. Penalty clauses invoked."},
    {"category": "construction", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} forays into data center construction. Adjacent opportunity tapped."},
    {"category": "construction", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} debt-to-equity ratio crosses 1.5. Leverage concerns mount."},
    {"category": "construction", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} margin on new orders improves 150 bps on better contract structuring."},
    {"category": "construction", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} promoter pledge rises to 60%. Governance concerns weigh on stock."},
    {"category": "construction", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} joint venture with global infrastructure fund opens new bidding opportunities."},
    {"category": "construction", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} land acquisition hurdles slow project progress in key state."},
    {"category": "construction", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} emerges as lowest bidder for metro rail project. Order book to swell."},
    {"category": "construction", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} steel procurement costs rise. Fixed-price contract margins under pressure."},
    {"category": "construction", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "construction", "linked_driver": "news_severity",
     "template_text": "{company} asset monetization plan via InvIT. De-leveraging strategy gains traction."},

    # ── Real Estate ─────────────────────────────────────────────────────
    {"category": "realestate", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} pre-sales hit all-time high on strong demand in premium segment."},
    {"category": "realestate", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} project completion delayed. RERA penalty and customer refunds loom."},
    {"category": "realestate", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} commercial leasing activity robust. Office space absorption rises 20%."},
    {"category": "realestate", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} inventory overhang in luxury segment. Demand shift to affordable housing."},
    {"category": "realestate", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} land bank acquisition in prime location. Future development potential unlocked."},
    {"category": "realestate", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} debt refinancing talks with NBFC stall. Liquidity concerns resurface."},
    {"category": "realestate", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} collections efficiency improves. Operating cash flow turns positive."},
    {"category": "realestate", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} alleged diversion of homebuyer funds under investigation. Credibility hit."},
    {"category": "realestate", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} REIT listing of office assets gains shareholder approval. Monetization ahead."},
    {"category": "realestate", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} new launches disappoint in Q. Tepid response from homebuyers."},
    {"category": "realestate", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} rental income grows on indexation benefits and lease renewals."},
    {"category": "realestate", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} input costs rise on cement and steel price inflation. Construction margins squeezed."},
    {"category": "realestate", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} strategic joint venture with global investor for mixed-use township project."},
    {"category": "realestate", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} flat buyer protests intensify. Delivery timeline uncertainty persists."},
    {"category": "realestate", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "realestate", "linked_driver": "news_severity",
     "template_text": "{company} RERA compliance rating upgraded. Brand trust improves among homebuyers."},

    # ── Telecommunications ──────────────────────────────────────────────
    {"category": "telecom", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} ARPU improves on tariff hike. Premium subscriber adds accelerate."},
    {"category": "telecom", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} subscriber churn rate spikes. Competitive tariff wars intensify in key circles."},
    {"category": "telecom", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} 5G coverage expands to 25 new cities. Broadband subscriber base crosses 20 million."},
    {"category": "telecom", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} AGR liability shock. Supreme Court verdict adds INR 10,000 Cr to dues."},
    {"category": "telecom", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} fiber-to-home connections grow 30%. Data consumption per user rising."},
    {"category": "telecom", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} spectrum auction participation may strain balance sheet. Capex worries persist."},
    {"category": "telecom", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} enterprise business wins large cloud connectivity deal. B2B momentum strong."},
    {"category": "telecom", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} interconnect usage charge regulation change impacts revenue."},
    {"category": "telecom", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} tower infrastructure arm monetization plan. NAV unlocking in sight."},
    {"category": "telecom", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} quality of service complaints rise. TRAI show cause notice issued."},
    {"category": "telecom", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} cost optimization program yields savings. EBITDA margin expands 200 bps."},
    {"category": "telecom", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} data breach exposes customer call records. Regulatory fine expected."},
    {"category": "telecom", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} satellite broadband partnership announced. Rural connectivity opportunity."},
    {"category": "telecom", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} spectrum usage charges rise. DoT policy change impacts profitability."},
    {"category": "telecom", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "telecom", "linked_driver": "news_severity",
     "template_text": "{company} international roaming revenue rebounds. Travel recovery benefits."},

    # ── Retail & E-commerce ─────────────────────────────────────────────
    {"category": "retail", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} same-store sales growth accelerates. Footfalls recover to pre-COVID levels."},
    {"category": "retail", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} gross margin compression on rapid discounting to fend off competition."},
    {"category": "retail", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} omnichannel strategy pays off. Online sales cross 25% of total revenue."},
    {"category": "retail", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} store closures in non-metro markets. Portfolio rationalization underway."},
    {"category": "retail", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} loyalty program crosses 5 million members. Repeat purchase rates improving."},
    {"category": "retail", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} inventory pile-up in apparel segment. Season-end discounts needed."},
    {"category": "retail", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} private label margins expand. Contribution to overall revenue rises to 15%."},
    {"category": "retail", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} employee attrition in supply chain division impacts last-mile delivery."},
    {"category": "retail", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} quick commerce pilot expands to 10 cities. Dark store network increases."},
    {"category": "retail", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} CCPA notice for misleading pricing practices. Consumer complaints rise."},
    {"category": "retail", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} festive season sales surpass estimates. Premium product mix improves."},
    {"category": "retail", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} rental costs rise on lease renewals. Store-level profitability under pressure."},
    {"category": "retail", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} supply chain automation reduces delivery costs by 12%."},
    {"category": "retail", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} GMV growth slows sequentially. Macro headwinds impact discretionary spending."},
    {"category": "retail", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "retail", "linked_driver": "news_severity",
     "template_text": "{company} enters new international market via strategic franchise agreement."},

    # ── Industrials & Capital Goods ─────────────────────────────────────
    {"category": "industrials", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} order book at record levels. Manufacturing PMI expansion boosts outlook."},
    {"category": "industrials", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} margins hit by rising raw material costs. Pricing power limited in competitive bids."},
    {"category": "industrials", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} secures largest-ever export order for heavy machinery. Global footprint expands."},
    {"category": "industrials", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} quality issues in exported equipment trigger client penalty clause."},
    {"category": "industrials", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} new manufacturing facility achieves zero-discharge status. ESG compliance ahead of peers."},
    {"category": "industrials", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} delays in raw material supply from China disrupt production schedule."},
    {"category": "industrials", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} aftermarket service revenue grows 25%. High-margin annuity stream strengthens."},
    {"category": "industrials", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} working capital days increase on slower client payments."},
    {"category": "industrials", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} bags defence manufacturing contract. Made in India initiative opens new vertical."},
    {"category": "industrials", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} technology obsolescence risk in legacy product line. R&D spend needed."},
    {"category": "industrials", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} capacity utilization crosses 90%. Operating leverage benefits flow through."},
    {"category": "industrials", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} import substitution threat from cheaper Chinese alternatives."},
    {"category": "industrials", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} inventory management system upgrade reduces holding costs 8%."},
    {"category": "industrials", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} labour union negotiations break down. Strike at main plant enters third week."},
    {"category": "industrials", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "industrials", "linked_driver": "news_severity",
     "template_text": "{company} collaborates with global OEM for technology transfer. Product competitiveness improves."},

    # ── Chemicals ───────────────────────────────────────────────────────
    {"category": "chemicals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} specialty chemicals volume grows 18%. Agrochem segment leads."},
    {"category": "chemicals", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} petrochemical spreads collapse on global oversupply. Capacity cuts likely."},
    {"category": "chemicals", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} USFDA approval for API manufacturing plant. Export opportunity unlocked."},
    {"category": "chemicals", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} unit explosion causes production halt. Regulatory probe ordered."},
    {"category": "chemicals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} agrochemical sales get boost from favourable monsoon forecast."},
    {"category": "chemicals", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} environmental clearance for new plant delayed by state pollution board."},
    {"category": "chemicals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} China-plus-one strategy benefits. Export enquiries up from European buyers."},
    {"category": "chemicals", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} input crude derivative prices surge. Profitability of commodities segment dented."},
    {"category": "chemicals", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} commissioned new continuous process plant. Cost savings of 15% expected."},
    {"category": "chemicals", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} anti-dumping duty on key product expires. Chinese imports flood market."},
    {"category": "chemicals", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} R&D patent filings cross 50. Innovation pipeline strengthening."},
    {"category": "chemicals", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} effluent treatment violation leads to plant shut down by green tribunal."},
    {"category": "chemicals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} fluorochemicals business enters high-growth EV battery material supply chain."},
    {"category": "chemicals", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} freight costs rise on Red Sea disruption. Export logistics impacted."},
    {"category": "chemicals", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "chemicals", "linked_driver": "news_severity",
     "template_text": "{company} backward integration into key intermediate reduces dependence on imports."},

    # ── Media & Entertainment ───────────────────────────────────────────
    {"category": "media", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} movie slate performs well. Box office collection crosses INR 500 Cr milestone."},
    {"category": "media", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} advertising revenue declines as corporate spends tighten."},
    {"category": "media", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} OTT subscriber base crosses 10 million. Original content strategy pays off."},
    {"category": "media", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} TRAI tariff order impacts subscription revenue. ARPU under pressure."},
    {"category": "media", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} radio business gains listenership share in top metro cities."},
    {"category": "media", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} print circulation declines accelerate. Digital subscription growth insufficient."},
    {"category": "media", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} sports broadcasting rights attract strong advertiser interest. Event pipeline full."},
    {"category": "media", "sentiment": "negative", "severity_band": "low",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} production costs spike on celebrity talent fees. Margin compression for new shows."},
    {"category": "media", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} music streaming arm turns EBITDA positive. Monetization improving."},
    {"category": "media", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} piracy concerns for marquee film release. Revenue loss estimated."},
    {"category": "media", "sentiment": "positive", "severity_band": "medium",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} digital advertising platform outperforms industry growth rate."},
    {"category": "media", "sentiment": "negative", "severity_band": "high",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} I&B ministry notice over content violation. License renewal at risk."},
    {"category": "media", "sentiment": "positive", "severity_band": "low",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} international film festival recognition for original production. Prestige boost."},
    {"category": "media", "sentiment": "negative", "severity_band": "medium",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} cord-cutting accelerates in cable business. Broadband migration needed."},
    {"category": "media", "sentiment": "positive", "severity_band": "high",
     "linked_event_category": "media", "linked_driver": "news_severity",
     "template_text": "{company} receives strategic investment from global media conglomerate. Valuation re-rating ahead."},
]


def seed(session: Session) -> None:
    # Validate linked_driver values against known price_driver factor definitions
    known_drivers = set(
        row.key for row in session.query(FactorDefinition).filter_by(factor_type="price_driver").all()
    ) or VALID_LINKED_DRIVERS

    all_events = MARKET_EVENTS + INDUSTRY_MARKET_EVENTS
    for evt in all_events:
        existing = session.query(MarketEvent).filter_by(name=evt["name"], category=evt["category"]).first()
        if existing is None:
            session.add(MarketEvent(**evt))

    all_templates = NEWS_TEMPLATES + INDUSTRY_NEWS_TEMPLATES
    for tmpl in all_templates:
        ld = tmpl.get("linked_driver", "")
        if ld and ld not in known_drivers:
            raise ValueError(
                f"NewsTemplate linked_driver '{ld}' is not a valid price_driver key. "
                f"Expected one of {sorted(known_drivers)}"
            )
        existing = session.query(NewsTemplate).filter_by(template_text=tmpl["template_text"]).first()
        if existing is None:
            session.add(NewsTemplate(**tmpl))


def main() -> None:
    database_url = os.environ.get(
        "DATABASE_URL",
        "postgresql+psycopg://stocksim:stocksim@localhost:5432/stocksim",
    )
    engine = create_engine(database_url)
    with Session(engine) as session:
        seed(session)
        session.commit()
    print("seed_events.py done.")


if __name__ == "__main__":
    main()
