"use client";

import * as React from "react";
import type { PriceHistoryItem } from "@/lib/api/types";

const W=1200,H=560,L=72,R=76,T=42,PRICE_BOTTOM=360,VOL_TOP=390,VOL_BOTTOM=500;
function sma(rows:PriceHistoryItem[],n:number){return rows.map((_,i)=>i<n-1?null:rows.slice(i-n+1,i+1).reduce((s,p)=>s+Number(p.close),0)/n)}
type PriceStyle="candles"|"heikin"|"bars"|"line"|"area";
function heikinAshi(rows:PriceHistoryItem[]):PriceHistoryItem[]{let previousOpen=0,previousClose=0;return rows.map((row,index)=>{const close=(Number(row.open)+Number(row.high)+Number(row.low)+Number(row.close))/4;const open=index===0?(Number(row.open)+Number(row.close))/2:(previousOpen+previousClose)/2;const converted={...row,open,close,high:Math.max(Number(row.high),open,close),low:Math.min(Number(row.low),open,close)};previousOpen=open;previousClose=close;return converted})}
export function OhlcvTerminal({ticker,data}:{ticker:string;data:PriceHistoryItem[]}){
 const [range,setRange]=React.useState<30|90|180>(90),[hover,setHover]=React.useState<number|null>(null),[showSma,setShowSma]=React.useState(true),[showVwap,setShowVwap]=React.useState(true),[priceStyle,setPriceStyle]=React.useState<PriceStyle>("candles");
 const persistedRows=data.slice(-range),rows=priceStyle==="heikin"?heikinAshi(persistedRows):persistedRows, vals=rows.flatMap(p=>[Number(p.low),Number(p.high)]), lo=Math.min(...vals,0),hi=Math.max(...vals,1),pad=(hi-lo)*.08||1,min=lo-pad,max=hi+pad,span=max-min;
 const x=(i:number)=>L+(i+.5)/Math.max(1,rows.length)*(W-L-R), y=(v:number)=>T+(max-v)/span*(PRICE_BOTTOM-T), maxVol=Math.max(...rows.map(p=>Number(p.volume)),1), vy=(v:number)=>VOL_BOTTOM-v/maxVol*(VOL_BOTTOM-VOL_TOP), bw=Math.max(2,Math.min(12,(W-L-R)/Math.max(rows.length,1)*.62));
 const avg20=sma(rows,20), cumulative=rows.reduce<Array<{pv:number;v:number}>>((a,p,i)=>{const prev=a[i-1]??{pv:0,v:0};a.push({pv:prev.pv+((Number(p.high)+Number(p.low)+Number(p.close))/3)*Number(p.volume),v:prev.v+Number(p.volume)});return a},[]),vwap=cumulative.map(p=>p.v?p.pv/p.v:0);
 const path=(values:Array<number|null>)=>values.map((v,i)=>v==null?"":`${i&&values[i-1]!=null?"L":"M"}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(" "); const active=hover??Math.max(0,rows.length-1),p=rows[active];
 const change=p?((Number(p.close)/Number(p.open)-1)*100):0,volAvg=rows.reduce((s,r)=>s+Number(r.volume),0)/Math.max(1,rows.length);
 const closePath=path(rows.map(row=>Number(row.close))),closeArea=`${closePath} L${x(Math.max(0,rows.length-1))},${PRICE_BOTTOM} L${x(0)},${PRICE_BOTTOM} Z`;
 return <section className="overflow-hidden border border-[#263246] bg-[#05090e]">
  <header className="flex flex-wrap items-center gap-4 border-b border-[#1b2635] bg-[#0a1018] px-4 py-3 font-mono"><div><div className="text-[9px] uppercase tracking-[.16em] text-[#67758a]">Scenario security monitor</div><div className="mt-1 text-base font-bold tracking-[.06em] text-white">{ticker} <span className="font-normal text-[#68778d]">/ OHLCV</span></div></div>{p&&<div className="grid grid-cols-6 gap-5 text-right text-[11px]"><Read label="Open" value={Number(p.open)}/><Read label="High" value={Number(p.high)}/><Read label="Low" value={Number(p.low)}/><Read label="Close" value={Number(p.close)} tone={change>=0?"up":"down"}/><Read label="Change" value={`${change>=0?"+":""}${change.toFixed(2)}%`} tone={change>=0?"up":"down"}/><Read label="Volume" value={Number(p.volume).toLocaleString()}/></div>}
  <div className="ml-auto flex items-center gap-1"><label className="mr-1 flex items-center gap-2 border border-[#324158] bg-[#070b10] px-2 py-1 text-[8px] uppercase tracking-[.1em] text-[#66758a]">Style<select aria-label="Price chart style" value={priceStyle} onChange={e=>setPriceStyle(e.target.value as PriceStyle)} className="bg-transparent font-mono text-[9px] font-bold text-[#dbe5f2] outline-none"><option value="candles">Candles</option><option value="heikin">Heikin Ashi</option><option value="bars">OHLC Bars</option><option value="line">Line</option><option value="area">Area</option></select></label>{([30,90,180] as const).map(v=><button key={v} onClick={()=>setRange(v)} className={`border px-2 py-1 text-[9px] ${range===v?"border-[#f3b33d] bg-[#f3b33d]/10 text-[#f3b33d]":"border-[#263246] text-[#78869a]"}`}>{v}D</button>)}<button onClick={()=>setShowSma(v=>!v)} className={`border px-2 py-1 text-[9px] ${showSma?"border-[#5d9cff] text-[#5d9cff]":"border-[#263246] text-[#78869a]"}`}>SMA20</button><button onClick={()=>setShowVwap(v=>!v)} className={`border px-2 py-1 text-[9px] ${showVwap?"border-[#d3a83d] text-[#d3a83d]":"border-[#263246] text-[#78869a]"}`}>VWAP</button></div></header>
  <svg viewBox={`0 0 ${W} ${H}`} className="h-[560px] w-full" onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect(),px=(e.clientX-r.left)/r.width*W;setHover(Math.max(0,Math.min(rows.length-1,Math.floor((px-L)/(W-L-R)*rows.length))))}} onMouseLeave={()=>setHover(null)} role="img" aria-label={`${ticker} candlestick and volume chart`}>
   <rect x={L} y={T} width={W-L-R} height={PRICE_BOTTOM-T} fill="#070c12"/><rect x={L} y={VOL_TOP} width={W-L-R} height={VOL_BOTTOM-VOL_TOP} fill="#060a0f"/>
   {Array.from({length:6},(_,i)=>min+span*i/5).map(v=><g key={v}><line x1={L} x2={W-R} y1={y(v)} y2={y(v)} stroke="#16202d"/><text x={L-10} y={y(v)+4} textAnchor="end" fill="#617087" fontSize="11" fontFamily="monospace">{v.toFixed(2)}</text></g>)}
   <defs><linearGradient id="ohlcv-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4e94ff" stopOpacity=".35"/><stop offset="1" stopColor="#4e94ff" stopOpacity="0"/></linearGradient></defs>
   {(priceStyle==="line"||priceStyle==="area")&&<>{priceStyle==="area"&&<path d={closeArea} fill="url(#ohlcv-area)"/>}<path d={closePath} fill="none" stroke="#5d9cff" strokeWidth="2"/></>}
   {rows.map((r,i)=>{const up=Number(r.close)>=Number(r.open),c=up?"#3dd598":"#ff6370",showOhlc=priceStyle==="candles"||priceStyle==="heikin"||priceStyle==="bars";return <g key={r.sim_date}>{showOhlc&&<><line x1={x(i)} x2={x(i)} y1={y(Number(r.high))} y2={y(Number(r.low))} stroke={c}/>{priceStyle==="bars"?<><line x1={x(i)-bw/2} x2={x(i)} y1={y(Number(r.open))} y2={y(Number(r.open))} stroke={c}/><line x1={x(i)} x2={x(i)+bw/2} y1={y(Number(r.close))} y2={y(Number(r.close))} stroke={c}/></>:<rect x={x(i)-bw/2} y={Math.min(y(Number(r.open)),y(Number(r.close)))} width={bw} height={Math.max(1.5,Math.abs(y(Number(r.open))-y(Number(r.close))))} fill={c}/>}</>}<rect x={x(i)-bw/2} y={vy(Number(r.volume))} width={bw} height={VOL_BOTTOM-vy(Number(r.volume))} fill={c} opacity=".42"/></g>})}
   {showSma&&<path d={path(avg20)} fill="none" stroke="#5d9cff" strokeWidth="1.5"/>}{showVwap&&<path d={path(vwap)} fill="none" stroke="#d3a83d" strokeWidth="1.3" strokeDasharray="5 4"/>}
   {p&&<><line x1={x(active)} x2={x(active)} y1={T} y2={VOL_BOTTOM} stroke="#90a0b7" strokeDasharray="2 4"/><line x1={L} x2={W-R} y1={y(Number(p.close))} y2={y(Number(p.close))} stroke="#90a0b7" strokeDasharray="2 4"/><text x={x(active)} y={H-22} textAnchor="middle" fill="#93a1b5" fontSize="11" fontFamily="monospace">{p.sim_date}</text></>}
   <text x={L} y={VOL_TOP-10} fill="#65748a" fontSize="10" fontFamily="monospace">VOLUME · AVG {Math.round(volAvg).toLocaleString()}</text><text x={W-R} y={H-22} textAnchor="end" fill="#65748a" fontSize="10" fontFamily="monospace">{priceStyle==="heikin"?"HEIKIN ASHI · DERIVED FROM PERSISTED OHLCV":"CROSSHAIR · REAL PERSISTED OHLCV"}</text>
  </svg>
 </section>
}
function Read({label,value,tone}:{label:string;value:number|string;tone?:"up"|"down"}){return <div><div className="text-[8px] uppercase tracking-[.12em] text-[#66758a]">{label}</div><div className={tone==="up"?"text-[#3dd598]":tone==="down"?"text-[#ff6370]":"text-[#dbe5f2]"}>{typeof value==="number"?value.toFixed(2):value}</div></div>}
