"use client";
import * as React from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ResearchChartDeck } from "@/components/future-lab/ResearchChartDeck";
import { Metric, ResultShell } from "@/components/future-lab/ResultShell";
import { useTimelineAnalytics } from "@/lib/api/hooks/useSimulation";
import { usePriceHistory } from "@/lib/api/hooks/useCompany";
import { useMarketGrid } from "@/lib/api/hooks/useMarket";

export default function ResultOverview() {
 const id=Number(useParams<{timelineId:string}>().timelineId),{data,isLoading}=useTimelineAnalytics(id),{data:market}=useMarketGrid(id),[ticker,setTicker]=React.useState("");
 const universe=market?.companies??[]; React.useEffect(()=>{if(!ticker&&data?.best_companies[0])setTicker(data.best_companies[0].ticker)},[ticker,data]); const {data:history=[]}=usePriceHistory(ticker,id);
 if(isLoading||!data)return <ResultShell timelineId={id}><div className="grid h-72 place-items-center font-mono text-xs uppercase tracking-[.16em] text-[#f3b33d]">Loading persisted research dataset…</div></ResultShell>;
 const total=data.breadth.advancers+data.breadth.decliners+data.breadth.unchanged,advancePct=total?data.breadth.advancers/total*100:0;
 return <ResultShell timelineId={id}><div className="space-y-4">
  <section className="grid grid-cols-2 gap-px overflow-hidden border border-[#263246] bg-[#263246] md:grid-cols-4 xl:grid-cols-8"><Metric label="Ann. volatility" value={fmt(data.annualized_volatility_pct)}/><Metric label="Max drawdown" value={fmt(data.max_drawdown_pct)}/><Metric label="Advancers" value={String(data.breadth.advancers)}/><Metric label="Decliners" value={String(data.breadth.decliners)}/><Metric label="Advance ratio" value={`${advancePct.toFixed(1)}%`}/><Metric label="Volume regime" value={fmt(data.volume_change_pct,true)}/><Metric label="Liquidity shift" value={data.liquidity_change?.toFixed(3)??"—"}/><Metric label="Compared names" value={String(data.comparison?.companies_compared??0)}/></section>
  <div className="border border-[#263246] bg-[#0a1018] p-3"><div className="flex flex-wrap items-center gap-3"><div><div className="font-mono text-[9px] uppercase tracking-[.16em] text-[#657287]">Security drilldown</div><div className="mt-1 text-xs text-[#cad5e3]">Inspect any scenario constituent with full OHLCV telemetry</div></div><select value={ticker} onChange={e=>setTicker(e.target.value)} className="ml-auto min-w-64 border border-[#324158] bg-[#060a0f] px-3 py-2 font-mono text-xs text-white outline-none focus:border-[#f3b33d]">{universe.map(c=><option key={c.ticker} value={c.ticker}>{c.ticker} · {c.name}</option>)}</select>{ticker&&<Link href={`/companies/${ticker}`} className="border border-[#324158] px-3 py-2 font-mono text-[10px] uppercase text-[#8fa2ba] hover:border-[#f3b33d] hover:text-[#f3b33d]">Full security ↗</Link>}</div></div>
  <ResearchChartDeck analytics={data} ticker={ticker} history={history}/>
  <div className="grid gap-4 xl:grid-cols-[1fr_1fr_.7fr]"><Rank title="Leaders" rows={data.best_companies}/><Rank title="Laggards" rows={data.worst_companies}/><Breadth a={data.breadth.advancers} d={data.breadth.decliners} u={data.breadth.unchanged}/></div>
 </div></ResultShell>;
}
const fmt=(v:number|null,sign=false)=>v==null?"—":`${sign&&v>=0?"+":""}${v.toFixed(2)}%`;
function Rank({title,rows}:{title:string;rows:Array<{ticker:string;name:string;sector:string;return_pct:number;final_close:number;final_intrinsic_value:number}>}){return <section className="border border-[#263246] bg-[#070b11]"><header className="border-b border-[#1b2635] px-4 py-3 font-mono text-xs font-semibold uppercase tracking-[.1em] text-[#dbe5f2]">{title}</header><div>{rows.map((r,i)=>{const gap=(r.final_close/r.final_intrinsic_value-1)*100;return <Link href={`/companies/${r.ticker}`} key={r.ticker} className="grid grid-cols-[28px_1fr_auto] items-center gap-2 border-b border-[#141d28] px-3 py-2.5 font-mono text-[11px] hover:bg-white/[.025]"><span className="text-[#56657a]">{String(i+1).padStart(2,"0")}</span><span><b className="text-white">{r.ticker}</b><small className="ml-2 text-[#68778c]">{r.sector}</small></span><span className="text-right"><b className={r.return_pct>=0?"text-[#3dd598]":"text-[#ff6370]"}>{r.return_pct>=0?"+":""}{r.return_pct.toFixed(2)}%</b><small className="ml-3 text-[#69788e]">GAP {gap>=0?"+":""}{gap.toFixed(1)}%</small></span></Link>})}</div></section>}
function Breadth({a,d,u}:{a:number;d:number;u:number}){const total=a+d+u||1;return <section className="border border-[#263246] bg-[#070b11] p-4"><h2 className="font-mono text-xs font-semibold uppercase tracking-[.1em] text-[#dbe5f2]">Market breadth</h2><div className="mt-5 flex h-4 overflow-hidden"><i className="bg-[#20a875]" style={{width:`${a/total*100}%`}}/><i className="bg-[#59677a]" style={{width:`${u/total*100}%`}}/><i className="bg-[#cf4855]" style={{width:`${d/total*100}%`}}/></div><div className="mt-5 grid grid-cols-3 gap-2 font-mono text-center"><B label="Advancing" value={a} c="#3dd598"/><B label="Flat" value={u} c="#94a3b8"/><B label="Declining" value={d} c="#ff6370"/></div><p className="mt-5 text-[10px] leading-5 text-[#66758a]">Breadth is calculated from persisted terminal closes versus each company’s branch-point close.</p></section>}
function B({label,value,c}:{label:string;value:number;c:string}){return <div><div className="text-xl font-bold" style={{color:c}}>{value}</div><div className="mt-1 text-[8px] uppercase tracking-[.1em] text-[#657287]">{label}</div></div>}
