"""add con_calls table -- quarterly conference-call transcripts

Adds the ConCall model (db/models/concalls.py): one row per
(company_id, fiscal_period), generated by engine/concalls.py at the same
quarter boundary where engine.orchestrator._refresh_fundamentals creates that
quarter's financial statements. tone/tone_score/guidance_revenue_growth feed
forward into the next quarter's revenue-growth generation (see
engine.orchestrator._load_concall_guidance_signal).

Revision ID: 0013
Revises: 0012
Create Date: 2026-07-18
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: Union[str, None] = "0012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    json_type = postgresql.JSONB() if bind.dialect.name == "postgresql" else sa.JSON()

    op.create_table(
        "con_calls",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("company_id", sa.Integer(), sa.ForeignKey("companies.id", ondelete="CASCADE"), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=False),
        sa.Column("call_date", sa.Date(), nullable=False),
        sa.Column("performance_bucket", sa.String(length=10), nullable=False),
        sa.Column("tone", sa.String(length=20), nullable=False),
        sa.Column("tone_score", sa.Numeric(), nullable=False),
        sa.Column("guidance_revenue_growth", sa.Numeric(), nullable=False),
        sa.Column("statements", json_type, nullable=False),
        sa.Column("driver_deltas", json_type, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("company_id", "fiscal_period", name="uq_con_calls_company_period"),
    )

    # SQLite (used in tests) does not reliably support adding CHECK constraints
    # via ALTER, and op.create_table above already runs on a fresh table there,
    # so guard the same way 0010_add_news_type.py does: only add these via a
    # separate batch op on dialects that support it cleanly.
    if bind.dialect.name != "sqlite":
        op.create_check_constraint(
            "ck_con_calls_performance_bucket",
            "con_calls",
            "performance_bucket in ('beat', 'inline', 'miss')",
        )
        op.create_check_constraint(
            "ck_con_calls_tone",
            "con_calls",
            "tone in ('confident', 'measured', 'cautious', 'defensive', 'evasive')",
        )
        op.create_check_constraint(
            "ck_con_calls_tone_score_range",
            "con_calls",
            "tone_score >= -1 and tone_score <= 1",
        )

    op.create_index("ix_con_calls_company_id", "con_calls", ["company_id"])


def downgrade() -> None:
    op.drop_index("ix_con_calls_company_id", table_name="con_calls")
    op.drop_table("con_calls")
